# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/image.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gz/msgs/image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/image.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\x98\x01\n\x05Image\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0c\n\x04step\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x33\n\x11pixel_format_type\x18\x06 \x01(\x0e\x32\x18.gz.msgs.PixelFormatType*\xbe\x02\n\x0fPixelFormatType\x12\x18\n\x14UNKNOWN_PIXEL_FORMAT\x10\x00\x12\n\n\x06L_INT8\x10\x01\x12\x0b\n\x07L_INT16\x10\x02\x12\x0c\n\x08RGB_INT8\x10\x03\x12\r\n\tRGBA_INT8\x10\x04\x12\r\n\tBGRA_INT8\x10\x05\x12\r\n\tRGB_INT16\x10\x06\x12\r\n\tRGB_INT32\x10\x07\x12\x0c\n\x08\x42GR_INT8\x10\x08\x12\r\n\tBGR_INT16\x10\t\x12\r\n\tBGR_INT32\x10\n\x12\r\n\tR_FLOAT16\x10\x0b\x12\x0f\n\x0bRGB_FLOAT16\x10\x0c\x12\r\n\tR_FLOAT32\x10\r\x12\x0f\n\x0bRGB_FLOAT32\x10\x0e\x12\x0f\n\x0b\x42\x41YER_RGGB8\x10\x0f\x12\x0f\n\x0b\x42\x41YER_BGGR8\x10\x10\x12\x0f\n\x0b\x42\x41YER_GBRG8\x10\x11\x12\x0f\n\x0b\x42\x41YER_GRBG8\x10\x12\x42\x1a\n\x0b\x63om.gz.msgsB\x0bImageProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013ImageProtos'
  _globals['_PIXELFORMATTYPE']._serialized_start=210
  _globals['_PIXELFORMATTYPE']._serialized_end=528
  _globals['_IMAGE']._serialized_start=55
  _globals['_IMAGE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
